"""empty message

Revision ID: 022ba12bc959
Revises: 35a8cfdc0e35
Create Date: 2020-04-27 10:46:24.801560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022ba12bc959'
down_revision = '35a8cfdc0e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('streak', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'total')
    op.drop_column('user', 'streak')
    # ### end Alembic commands ###
