"""empty message

Revision ID: 35a8cfdc0e35
Revises: 60fe89b3284c
Create Date: 2020-04-27 10:45:26.032355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a8cfdc0e35'
down_revision = '60fe89b3284c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('streak', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('total', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'total')
    op.drop_column('user', 'streak')
    # ### end Alembic commands ###
