"""empty message

Revision ID: b26c1ed86068
Revises: 022ba12bc959
Create Date: 2020-04-27 10:54:52.573158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b26c1ed86068'
down_revision = '022ba12bc959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'streak')
    op.drop_column('user', 'total')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('total', sa.INTEGER(), nullable=True))
    op.add_column('user', sa.Column('streak', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
